debug: true

logging:
  level:
    org:
      springframework:
        r2dbc: debug

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432
    name: hobby
    username: hobby
    password: hobby
    pool:
      enabled: true
      initial-size: 5
      max-size: 11
      max-idle-time: 1m
      validation-depth: local
      validation-query: select 1
